name: Lighthouse CI

on: pull_request

jobs:
  lighthouse:
    if: github.event.pull_request.draft == false
    permissions:
      contents: read
      pull-requests: write
    uses: danibsheehan/dani-actions/.github/workflows/lighthouse-ci.yml@v17
    with:
      build-command: 'VITE_API_BASE=https://statsapi.mlb.com/api/v1 npm run build'
